planetscale/cli

internal/cmd/auth/login.go
internal/cmd/root.go
internal/printer/printer.go
internal/update/update.go

They don't work well. Let's disable them until we found out what the
problem is.

cmd: fix colors for Windows

---

internal/cmd/database/dump.go

This PR checks for the rows error as it's required after iterating. We
also remove a global variable and use it as local variable so it can't
be changed.

dump: check for DB rows error

---

internal/cmdutil/cmdutil.go

This PR improves the lookup for the `mysql` CLI also under the preferred homebrew location for Linux systems.
bonus: https://twitter.com/fatih/status/1395300098557480960

cmdutil: lookup homebrew installed `mysql` also under Linux

---

internal/cmd/auth/auth.go
internal/cmd/auth/login.go
internal/cmd/backup/backup.go
internal/cmd/branch/branch.go
internal/cmd/connect/connect.go
internal/cmd/database/database.go
internal/cmd/deployrequest/close.go
internal/cmd/deployrequest/deploy.go
internal/cmd/deployrequest/dr.go
internal/cmd/org/org.go
internal/cmd/shell/shell.go
internal/cmd/token/token.go

Signed-off-by: Jacques Grove <aquarapid@gmail.com>

Rework some of the short help messages

---

internal/cmd/root.go

This command is not fully implemented yet. Don't show it to the users.

cmd: disable backup command temporarily

---

internal/cmd/root.go

Restores the backup command's availability.

Enable backup command

---

internal/printer/printer.go

Fore more information checkout:
https://github.com/briandowns/spinner/pull/117#issuecomment-864986510

printer: fix clearing the progress/spinner output

---

internal/cmd/branch/branch.go
internal/cmd/branch/create.go

This pull request removes all references to `Notes` from branch creation.

Remove notes from branch create.

---

internal/cmd/connect/connect.go

closes: https://github.com/planetscale/cli/issues/322

connect: make DATABASE_URL environment variable name configurable

---

internal/cmd/deployrequest/diff.go

Fixes a small typo in a deploy-request does not exist error.

Fix typo in dr diff error message

---

script/bump-version.sh

see: https://github.com/buildkite/agent/issues/338#issuecomment-402017501

ci: make sure BuildKite have access to latest tags

---

internal/cmd/password/create.go
internal/cmd/password/delete.go
internal/cmd/password/list.go
internal/cmd/password/password.go

Couple of improvements to make the `pscale password` commands more nicer.

password: improve notice messages

---

internal/cmd/connect/connect.go

Fix for Windows colors

---

internal/cmd/connect/connect.go

We have a dedicated package that we use throughout the CLI to print messages to the user. The package already sets the stdout to `color.Output` and is the canonical way of using it for printing messages inside the CLI. The benefit of using this package is that we can change the output for all commands in just one place and that it can be disabled for other output formats, such as `JSON`.

connect: use internal printer package

---

internal/cmd/branch/delete.go
internal/cmd/database/delete.go

This pull request adds an extra check to check that a resource exists before prompting the user for confirmation. If it doesn't, we'll let them know it doesn't exist earlier, but if it does, then they can confirm the deletion of the resource.

Check that databases and branches exist before deletion confirmation.

---

internal/cmd/region/region.go

We tweaked the display of this information in the website, this matches that format.

Match Region display with the site

---

internal/cmd/connect/connect.go
internal/cmd/shell/shell.go

Make default certificate role `administrator` for `shell` & `connect`

Make default role administrator for shell & connect

---

internal/cmd/database/dump.go

content.
Signed-off-by: Jacques Grove <aquarapid@gmail.com>

Add --wheres argument for dump command, allowing filtering of table

---

.buildkite/pipeline.yml
Makefile
script/release.sh

Removes the docker inside docker to simplify and making publishing work.

Fix release process to remove docker in docker

---

Makefile

Update to latest Go

---

Dockerfile
Makefile
docker-compose.yml
docker/Dockerfile.licensed
internal/cmd/auth/login.go
internal/cmd/signup/signup.go
internal/config/config.go
internal/config/global.go
internal/dumper/dumper_test.go
internal/dumper/loader.go
internal/printer/printer.go
internal/update/update.go

Has the latest and greatest fixes.

Update to latest Go 1.19.1

---

README.md

Updated screenshot from @ceciliorz

Update screenshot w/ newer PlanetScale logo

---

internal/dumper/loader.go

When we hit an error inserting data, the current behavior of `restore-dump` is to log it, but not return it - this means that the command will exit with a 0 error code even if there was an error in the restore path, which can be misleading.
This will now emit an error per-table, and surfaces the first one that happens all the way up to the top of the command. 
cc @fatih. Not wedded to the approach, but it's straightforward.

Restore-dump: surface errors

---

internal/config/config.go
internal/config/global.go

Ensure we create the config directory before we write to it

---

Dockerfile
Makefile
docker-compose.yml
docker/Dockerfile.licensed

Bump to Go 1.19.5

---

go.mod
go.sum
internal/cmd/password/create.go
internal/cmd/password/create_test.go

Updates the password `display_name` to `name`

[Passwords] Update display name

---

.goreleaser.yml

This starts to build an experimental SBOM for inclusion with the PlanetScale CLI's archive distribution.

[goreleaser] build spdx BOM

---

internal/cmd/database/dump.go

Fixes: https://github.com/planetscale/cli/issues/578
If the DB is sleeping, we we now show a better error message.

Improve `dump` command error messages

---

internal/cmd/auth/auth.go
internal/cmd/auth/check.go

Fixes: https://github.com/planetscale/cli/issues/550
`pscale auth check` returns exit code 1 if not authenticated.

Add auth check command

---

README.md

Adding example for using `pscale` with GitHub Actions.

Add instructions for github actions

---

internal/cmd/root.go
internal/update/update.go

Looks just like before, and only does the lookup/notification once per 24h period. But now the check is done async during each command invocation, with a 250ms budget affordance to finish the check if it's running.
```
A new release of pscale is available: 0.146.0 → v0.148.0
https://github.com/planetscale/cli/releases/tag/v0.148.0
```
Currently, the update check only occurs if the command ends in error! This means that there's probably a ton of `pscale` installs that are way out of date and never get prompted to update, at least until they hit an error.

root: check for updates async, and not just on errors

---

internal/cmd/database/create.go

This pull request adds back in the confirmation step for anybody who is out of free databases, regardless of plan.

Prompt for creation of a paid database, also allow force creation.

---

internal/cmd/branch/switch.go

Fixes: https://github.com/planetscale/cli/issues/741
Found that the problem with this one was: when trying to create the branch, it was attempting to create within the wrong org. Which returned the NotFound error.
Now when that happens, we return a better error message.

Improve `switch` error message when DB does not exist in org

---

.goreleaser.yml

https://goreleaser.com/deprecations/#nfpmsreplacements

fix param name

---

go.mod
go.sum
internal/cmd/password/create.go
internal/cmd/password/password.go

The `ttl` is the time in seconds until the password will expire. A value of 0 means it will never expire.

Add ability to set password `ttl` via CLI

---

internal/cmd/ping/ping.go

This sets a default to 10 pings and helps smooth over variability with a single ping and returns an average.

ping: support a configurable number of pings

---

internal/cmd/ping/ping.go

The awkward part about this is because we need to "resolve" what the optimized endpoint mapped up to.
The "optimized" endpoints are kinda synthetic regions, so we can only determine what they point to by asking the endpoint.
We surface the information about the endpoint unofficially through the Server HTTP header on a response, so we can determine what we're pointing at by making a HEAD request to the optimized endpoint and parsing the Server header.
Short of adding a real "info" or something API to our edge layer, this is the best and most supported way and isn't intending to change in the nera or mid-term future. If we ever do explose some explicit `/info` endpoint (which we may), this can be changed to accommodate.

ping: map up endpoints to display names

---

Dockerfile.goreleaser

Revert "Remove root directory Dockerfile for goreleaser."

---

internal/cmd/branch/create.go

This flag is unused, removing it to simplify.

Remove --web on branch create

---

internal/cmd/branch/demote.go

I initially spotted:
```
16:30 $ nilness ./...          
/home/matt/src/github.com/planetscale/cli/internal/cmd/branch/demote.go:55:12: impossible condition: nil != nil
```
But there are a handful of things here that can be tidied up.

internal/cmd/branch: clean up demote

---

internal/update/update.go

The error handling here is pretty lax and could use tidying up. We don't want to throw away errors from writing the state file for sure.
Keep things scoped as tightly as possible and avoid passing a nil pointer into the JSON unmarshaler.

internal/update: cleanup and error handling

---

internal/cmd/database/create.go
internal/cmd/database/database.go

--notes is from a very early version of PlanetScale and has not been used anywhere for over 2 years.
Deprecating and removing it.

Deprecate --notes flag

---

internal/cmd/password/password.go
internal/cmd/password/renew.go

Depends on https://github.com/planetscale/planetscale-go/pull/193
```
$ ./pscale password list mattdb
ID             NAME                     BRANCH   USERNAME               ROLE     ROLE DESCRIPTION               TTL   TTL REMAINING   EXPIRED
-------------- ------------------------ -------- ---------------------- -------- ------------------------------ ----- --------------- ---------
jxsungtbhk3g   test-ttl                 main     m51veb3195rn79uoa4zm   reader   Can Read                        60              36   No
oddkvx4zj8y9   main-2023-11-11-e6qg9j   main     cc7elecd13x7gokz30sh   admin    Can Read, Write & Administer     0               0   No
```
We can renew our expiring password:
```
$ ./pscale password renew mattdb main jxsungtbhk3g
Password jxsungtbhk3g was successfully …
```

cmd/password: Add support for renewing an existing password

---

go.mod
go.sum
internal/cmd/database/create.go
internal/cmd/dataimports/lint.go
internal/cmd/dataimports/start.go

Scaler Pro is now the default when creating an import.

Update import to use scaler pro

---

internal/cmd/database/dump.go
internal/dumper/dumper.go

This will plumb this through for the various different options. It's not extremely pretty, but it will work for a pinch.

allow shard targeting with rdonly+replica, rdonly

---

internal/cmd/database/create.go

Default cluster size for `database create`

---

internal/cmd/workflow/cutover.go
internal/cmd/workflow/cutover_test.go
internal/cmd/workflow/reverse_cutover.go
internal/cmd/workflow/reverse_cutover_test.go
internal/cmd/workflow/workflow.go

This pull request is part of #999, where we implement the cutover command and the reverse cutover command as well.

Implement `cutover` and `reverse-cutover` commands for a workflow

---

internal/cmd/workflow/cancel.go
internal/cmd/workflow/cancel_test.go
internal/cmd/workflow/cutover.go
internal/cmd/workflow/cutover_test.go
internal/cmd/workflow/switch_traffic.go
internal/cmd/workflow/switch_traffic_test.go

There are some actions that can cause problems if done improperly. This adds a confirmation step for those actions.

Add confirmation for potentially dangerous workflow actions

---

internal/cmd/workflow/cutover.go

This seems like an important note to have.

Add note about require explicit routing rules to help text

---

internal/cmd/keyspace/settings.go
internal/cmd/keyspace/update_settings.go

Let's show these now that they are shipped 🎉

Unhide the keyspace settings and update-settings commands

---

internal/cmd/database/dump.go

The onboarding-demo database is no longer used.

Remove onboarding database from dump command

---

internal/cmd/branch/delete.go
internal/cmd/branch/delete_test.go
internal/cmd/branch/demote.go
internal/cmd/branch/demote_test.go
internal/cmd/branch/list.go
internal/cmd/branch/list_test.go
internal/cmd/branch/promote.go
internal/cmd/branch/promote_test.go

Continuing on with the pattern set in: https://github.com/planetscale/cli/pull/1067

Improve error messages for branch delete|promote|demote|list

---

go.mod
go.sum
internal/cmd/database/create.go

This pull request enables the creation of Postgres databases by adding a `kind` flag to the database create command.

Add `kind` flag to database creation
