- README.md
Upon invoking the pscale cli, an error occurs stating:
`Error: couldn't find the 'msyql' client required to run this command.`
To resolve this, you need to run:
`brew install mysql-client` and set the appropriate PATH to be able to use it.
Once this has been done, the Planetscale CLI works properly.
Environment:
M1 ARM Mac
MacOS 11.2.3
Homebrew 3.1.8
> Update README.md to include mysql-client install

- internal/cmd/auth/login.go
This PR introduces an improvement in the `pscale auth login` workflow.
Instead of failing immediately when we can't open a browser, we now
print the error and the URL so the user can manually continue.
fixes https://github.com/planetscale/beta/discussions/11
> auth: don't fail when we can't open a browser.

- internal/cmdutil/cmdutil.go
This is a follow-up to d19242e. From Homebrew:
> Homebrew’s pre-built binary packages (known as bottles) of many
> packages can only be used if you install in the default installation
> prefix, otherwise they have to be built from source. Building from
> source takes a long time, is prone to fail, and is not supported. Do
> yourself a favour and install to the default prefix so that you can use
> our pre-built binary packages. The default prefix is `/usr/local` for
> macOS on Intel, `/opt/homebrew` for macOS on ARM, and
> `/home/linuxbrew/.linuxbrew` for Linux. Pick another prefix at your peril!
https://docs.brew.sh/FAQ#why-should-i-install-homebrew-in-the-default-location
I've tested this on my M1 laptop with `go install ./...` on `94a168a7`.
Before this change, if I remove this from my …
> cmdutil: handle arm64 Homebrew prefix

- go.mod
- go.sum
- internal/cmd/database/dump.go
The Demo databases come up with a database name that doesn't match the name in PlanetScale, which is unique to demo databases.
This PR changes `pscale databsae dump` to look at all of the MySQL databases to look for either:
1. The DB that matches the name of the database
2. Any of the demo names
> `pscale database dump`: support Demo DBs

- internal/cmd/connect/connect.go
This gives the user some configuration over what protocol gets dropped into their `DATABASE_URL`. Some applications want `mysql`, and `mysql2` is often used in Rails. This defaults to what is there today, but allows the user to override it if they want. 
cc @iheanyi
> connect.go: let the user configure the protocol for DATABASE_URL

- internal/cmd/connect/connect.go
This adds a newline character to the connection established string so that any commands executed with `--execute` are printed cleanly on the following line.
**Before**
```shell
❯ pscale connect meow main --execute 'echo "Hello World"'
Secure connection to database meow and branch main is established!.
Local address to connect your application: 127.0.0.1:3306 (press ctrl-c to quit)Hello World
```
**After**
```shell
❯ pscale connect meow main --execute 'echo "Hello World"'
Secure connection to database meow and branch main is established!.
Local address to connect your application: 127.0.0.1:3306 (press ctrl-c to quit)
Hello World
```
> Add newline to connection established string

- go.mod
- go.sum
This update includes the new `NO_COLOR` environment variable which will come handy for both debugging and also for our users who don't like to see colors.
> go: update `github.com/fatih/color` to v1.12.0

- internal/cmd/connect/connect.go
This PR also handles the case when a socket fails to bind to a socket with exclusive access. For more information, check out the docs for the code `10013`: https://docs.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2
fixes: https://github.com/planetscale/cli/issues/265
> cmd/connect: handle Windows socket error 10013 (WSAEACCES)

- internal/cmd/root.go
This PR adds a new flag to disable color via the `--no-color`.
> cmd: add `--no-color` flag

- go.mod
- internal/printer/printer.go
This PR fixes the issue when coloring is disabled with the `NO_COLOR` environment variable. This would set `color.NoColor` variable to `true`, and hence in an environment where `NO_COLOR` is set, commands like `pscale auth login` would fail:
```
$ pscale auth login
Error: The 'login' command requires an interactive shell
```
With this change, if the user sets the `NO_COLOR` environment variable, it continues to work, but only the colors are disabled.
> tty: detect tty without depending on the color package

- internal/cmdutil/cmdutil.go
There is a difference between the classic `mysql` and the `mysqlsh` tool (which we were telling the users to install.
This PR fixes the links to suggest installing the correct tool from the official installation instructions.
> cmdutil: fix installation instructions for installing the mysql tool

- internal/cmd/connect/connect.go
This PR changes the behavior of the `--execute` flag.
Previously we would continue to serve the proxy even if the command with `--execute` would finish or fail. With this PR, we're changing it.  Instead of silently continuing to run, we're exiting entirely and shutting down the proxy. This is the correct behavior because the user explicitly has passed the `--execute` flag, and we should assume they only want to run the proxy for a single command.
If there are use cases where we don't want to exit, it's also easy to add it now. We could introduce a new flag that changes whether to call `cancel()` or not.
> connect: exit if `--execute` finishes

- Dockerfile
This PR introduces a simple `Dockerfile` that allows us to run `pscale` from within a container. Here are the commands if you want to try it out on your localhost:
```shell
docker build -t pscale:latest .
docker run -it --env PLANETSCALE_SERVICE_TOKEN= <token> --env PLANETSCALE_SERVICE_TOKEN_NAME=<name> --env PLANETSCALE_ORG=<org>  pscale shell planetscale main
``` 
Three environment variables are required to make it work:
```
PLANETSCALE_SERVICE_TOKEN
PLANETSCALE_SERVICE_TOKEN_NAME
PLANETSCALE_ORG
```
Users can also use the `--env-file` option (https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file) to set the environment variables.
There are several things that I'm planning to do in follow-up PRs: 
* Push to a public registry
* Configure …
> Add Dockerfile to run `pscale` as a container

- cmd/pscale/main.go
- internal/cmd/connect/connect.go
- internal/cmd/root.go
- internal/cmdutil/errors.go
This PR improves the `pscale connect` commands `--execute` flag. It now
captures the exit code of the command passed to the `--execute` flag and
exits with the returned code.  
I wrote a simple tool that exits with the code passed to the tools. As you see here, it exits with `0` or `2` and we successfully capture it:  
```
$ pscale connect planetscale main --execute 'demo 0'
Secure connection to database planetscale and branch main is established!.
Local address to connect your application: 127.0.0.1:3306 (press ctrl-c to quit)
exiting with 0
$ echo $status
0
$ pscale connect planetscale main --execute 'demo 2'
Secure connection to database planetscale and branch main is established!.
Local address to connect your application: 127.0.0.1:3306 (press ctrl-c to quit)
exiting with 2
Error: …
```
> cmd/connect: return exit status of `--execute` flag

- .goreleaser.yml
- Dockerfile
- Dockerfile.goreleaser
- Makefile
This PR adds the docker image build and push instructions for local development and adds Docker build/push integration into `goreleaser`. On **localhost**, to build and push the image, use the following commands:
```
make build-image
make push 
```
This will build the image and push it to the Docker hub (assuming you have the permission to make the push). The `make` tasks are mainly for debugging and making sure we can build an image if `goreleaser` is broken or need manual intervention.
---
The goreleaser integration uses a different Dockerfile, named `Dockerfile.goreleaser`. The `Dockerfile.goreleaser` is simpler than the base `Dockerfile` file because `goreleaser` does the heavy lifting of building the binary. To build and push with `goreleaser`, run the following command (assuming you …
> Dockerfile: add build and push instructions

- cmd/pscale/main.go
- internal/cmd/root.go
This PR simplifies the execution and printing of the error message of the root command. Previously, we would print an error message inside the `cmd/pscale` package and the `internal/cmd` package. The exit status returned from the root command would also be shadowed from another function call. In our case, this was the `updater` logic. Having these two operations in different places makes it difficult to debug and also introduces bugs (see: https://github.com/planetscale/cli/issues/283#issuecomment-852393281)
With this PR, the `cmd/pscale` main package only exits with a given exit code. It's as minimal as its gets. By making sure we're also just exiting with a code in the main package, we also set an artificial boundary. This way, we don't print any message accidentally inside the `main` …
> cmd: improve execution of the root command

- internal/cmd/org/show.go
- internal/cmdutil/cmdutil.go
Not all users want to use access tokens while using the CLI. Some users prefer to create a service token and use that. However, our warning assumes that pscale was called interactively, and the user intends to use an access token.
This PR improves the message to make it clear that there are other options.
> cmd: improve the authentication warning for service token's

- internal/cmd/org/switch.go
We're checking the organization, so I think it's better if we tell it that way.
> cmd/org: improve messaging during validation

- internal/cmd/branch/create.go
- internal/cmd/completion.go
- internal/cmd/database/show.go
- internal/cmd/org/switch.go
- internal/cmd/root.go
This PR adds shell (Bash, Zsh, fish, and PowerShell) completions for all our subcommands and flags.
We also added a couple of dynamic completions to make it easy to choose
certain arguments, such as:
* `pscale org switch <complete organization ...>`
* `pscale branch create <complete database...>`
* `pscale database show <complete database...>`
Here is a demo that shows it in action for fish shell:
https://user-images.githubusercontent.com/438920/121519579-8a0c4900-c9fa-11eb-8fd8-f56737678a02.mp4
> cmd: add shell completion for subcommands

- go.mod
- go.sum
- internal/cmd/branch/create.go
- internal/cmd/branch/create_test.go
- internal/cmd/branch/switch.go
This pull request fixes the branch creation command to use the flattened `CreateDatabaseBranchRequest` object from the new `planetscale-go` version.
> Update `planetscale-go` and fix branch creation command

- go.mod
- go.sum
- internal/cmd/branch/create.go
- internal/cmd/branch/create_test.go
- internal/cmd/database/create.go
- internal/cmd/database/create_test.go
This pull request adds the `--region` flag to the `branch create` and `database create` commands so we can eventually make regional databases and branches as we add them in. Also, we can get some auto-completion action going with hitting the regions API to pre-populate things.
Depends on https://github.com/planetscale/planetscale-go/pull/70 landing first and we gotta update our `planetscale-go` version.
> Add region flag to database and branch creation commands

- .gitignore
- .goreleaser.yml
- script/completions
This PR includes the completions script generated by `pscale completion`
and adds them for the macOS and Linux packages. That way, the user
doesn't have to generate and install the completion scripts manually.
> completion: include completions in archives, linux packages and homebrew

- internal/cmd/root.go
Currently our `main` branch is broken due the latest `spf13/viper`
upgrade to `v1.8.0`. Viper now returns an error if we try to bind to a
nil flag (flag's that are not yet defined).
Fixes the following error:
```
$ pscale
Error: flag for "org" is nil
````
> cmd: don't bind to nil flags

- .licenses/go/github.com/AlecAivazis/survey/v2.dep.yml
- .licenses/go/github.com/AlecAivazis/survey/v2/core.dep.yml
- .licenses/go/github.com/AlecAivazis/survey/v2/terminal.dep.yml
- .licenses/go/github.com/briandowns/spinner.dep.yml
- .licenses/go/github.com/planetscale/planetscale-go/planetscale.dep.yml
- .licenses/go/github.com/spf13/viper.dep.yml
- .licenses/go/go.uber.org/zap.dep.yml
- .licenses/go/go.uber.org/zap/buffer.dep.yml
- .licenses/go/go.uber.org/zap/internal/bufferpool.dep.yml
- .licenses/go/go.uber.org/zap/internal/color.dep.yml
- .licenses/go/go.uber.org/zap/internal/exit.dep.yml
- .licenses/go/go.uber.org/zap/zapcore.dep.yml
- .licenses/go/golang.org/x/term.dep.yml
- go.mod
- go.sum
`licensed` fails if a license can't be parsed properly. This happened during the dependabot PR https://github.com/planetscale/cli/pull/318 when the `survey` package introduced a new dependency.
This PR updates the `survey` package and fixes the licensed cache file.
> Update github.com/AlecAivazis/survey/v2 and licensed cache

- .buildkite/pipeline.yml
- script/release.sh
This PR adds a fully automated release pipeline for the CLI. PlanetScale authorized people will release a new version of the CLI by signing into BuildKite and then pressing the `Release!` button. The button will only be shown in the `main` branch.
> buildkite: add release step

- .gitignore
Sometimes I vendor for local development purposes. We don't use vendoring, though. Let's ignore it, so we don't purposely add any code changes from a vendor folder.
> Ignore the `vendor/` folder

- internal/cmd/branch/branch.go
- internal/cmd/branch/status_test.go
This information is not used anymore. Just show the readiness of the
branch. We're going to either remove this branch or overhaul the
usage in the future.
> branch: status information is not used anymore

- go.mod
- go.sum
- internal/proxyutil/remotesource.go
This ensures we can use the multi CA support and that that is all working now.
> Update to latest planetscale-go and sql-proxy

- README.md
It looks like after replacing our old BuildKite pipeline, the link to the badge was invalidated. Let's replace it with the new one.
> README: update correct URL to the build badge

- .buildkite/pipeline.yml
- docker-compose.yml
This fixes some security issues, mostly one where a TLS client can be made to crash with a forged certificate.
> Update to the latest Go 1.16.6

- go.mod
- go.sum
- internal/cmd/token/addaccess_test.go
- internal/cmd/token/showaccess_test.go
This fixes the bugs we are having with users creating service-tokens
```go
~$ pscale service-token add-access te2okcpjdb5t connect_branch --database again
Error: json: cannot unmarshal string into Go struct field ServiceTokenAccess.data.id of type int
~$ pscale service-token show-access te2okcpjdb5t
Error: json: cannot unmarshal string into Go struct field ServiceTokenAccess.data.id of type int
```
> Update to the latest planetscale go client

- internal/cmd/token/addaccess.go
Example syntax should use `pscale service-token...`
> Fix add-access example text

- internal/auth/authenticator.go
Moves away from `device_code` and uses the official grant type for authorization codes.
> Use official authorization grant type.

- internal/cmd/token/list.go
Hello, `@planetscale`! 👋  🌍 
This PR shows a friendly message if there are no service tokens to list:
```
➜  ~ pscale service-token list  
No service tokens have been created yet.
```
This copies the same pattern when a client asks for a list of databases, but there aren't any:
https://github.com/planetscale/cli/blob/73c0ca7b9147fe5c582293a68c5d451998b3b2bd/internal/cmd/database/list.go#L58-L61
This is my first time contributing to a CLI based on Cobra -- I'd be happy to write tests for these, if it's expected/welcome with some pointers. Thanks ya'll! :v:
> Feature: show friendly message if there are no tokens

- internal/cmd/database/dump.go
- internal/cmd/database/restore.go
- internal/cmd/shell/shell.go
These values are hardcoded right now and are not actually providing anything useful. The local proxy always uses root with no password anyway, so we can depend on that.
> Cleanup usage of database credentials

- internal/cmd/branch/create.go
- internal/cmd/database/create.go
This pull request unhides the `--region` flag for database and branch creation.
> Unhide region flag for branches and databases

- .gitignore
- go.mod
- go.sum
- internal/proxyutil/remotesource.go
This updates all the dependencies of the CLI with the cleaned up logic around TLS validation.
We still need to make some last server side updates before this can be safely merged and a new CLI version can be released.
> Update dependencies with cleaned up validation logic

- go.mod
- go.sum
- internal/cmd/password/create.go
- internal/cmd/password/create_test.go
- internal/cmd/password/delete.go
- internal/cmd/password/delete_test.go
- internal/cmd/password/list.go
- internal/cmd/password/list_test.go
- internal/cmd/password/password.go
- internal/cmd/root.go
This PR changes the `pscale password list` subcommand to list all branches. The following changes were made:
* Renamed the `passwords` package to `package` (packages in Go should be singular)
* Added a new header with the name `Branch` to the output, so the user can see which password belongs to which branch
* `pscale password list database` now lists all passwords from all branches. This is now the same behavior we see in the UI
* `pscale password list database branch` lists all passwords for the given `branch`.
Depends on https://github.com/planetscale/cli/pull/367
> passwords: support listing all passwords

- internal/cmd/branch/switch.go
Let's return the database and organization name so the user invoking it
knows what's going on.
> branch: return db and org name for better debugging

- internal/cmd/shell/shell.go
- internal/update/update.go
This makes it possible to use `pscale shell` to run small SQL scripts
against a database branch from shell scripts.
This is behind an environment variable for now, while we make sure there
aren't unintended consequences. We may remove the check entirely at a
later time.
> Add override to allow non-interactive use of `pscale shell`

- internal/cmd/deployrequest/deploy.go
`pscale deploy-request deploy <db> <deploy-request-id>` actually adds the deploy-request to the queue to be deployed, but the current success message tells you that the deploy-request has *been* deployed already.
This modifies the success message for clarity. Ideally, it'd also print the URL to view the deploy request on the Planetscale Dashboard.
> Clarify success message of deploy command

- internal/cmdutil/cmdutil.go
It's not easy to configure the `mysql` CLI for each OS. Our docs are
more extensive and helpful, hence link to the docs page.
fixes: https://github.com/planetscale/cli/issues/384
> cmdutil: link to our own documentation

- go.mod
- go.sum
- internal/cmd/backup/backup.go
- internal/cmd/backup/restore.go
- internal/cmd/backup/restore_test.go
- internal/cmd/branch/branch.go
- internal/cmd/branch/create.go
Add two commands to restore a backup to a new branch. Requires https://github.com/planetscale/planetscale-go/pull/94.
pscale branch create <db> <name> --restore <backup>
pscale backup restore <db> <name> <backup>
> Restore backup to new branch

- internal/cmd/database/restore.go
Avoid confusion between restoring a hosted backup and restoring from a local dump file.
> Rename restore command to restore-dump

- internal/cmd/database/dump.go
After the changes in https://github.com/planetscale/cli/commit/98c6fd0f3357afb94633d08d3e509ed531828b10, the `pscale database dump` command started throwing an `EOF` error. The reason for that is, the `github.com/xelabs/go-mysqlstack` package expects the password to be non-empty. Adding a placeholder value (with no meaning) fixes it.
This change is temporary and we're going to remove it once we remove the `proxy` and move using connection strings.
> dump: add a placeholder password to fix `EOF` error

- internal/cmd/backup/restore.go
- internal/cmd/branch/branch.go
- internal/cmd/branch/create.go
- internal/cmd/branch/promote.go
- internal/cmd/branch/show.go
Instead of creating a new exported method, we can export the existing
`toDatabaseBranch` method. 
I also removed the import alias `b`, because
one character identifier is rarely used for naming packages.
> branch: export `toDatabaseBranch` and remove one char package alias

- internal/cmd/database/restore.go
Applies the temporary fix from https://github.com/planetscale/cli/pull/392 to the `dump-restore` command.
> dump-restore: add a placeholder password to fix EOF error

- internal/cmd/region/region.go
Given that we're adding more locations in the same regions, this adds the geographical location to the output for a region. This allows users to disambiguate where the the regions are actually located.
```
NAME (6)       SLUG           ENABLED
-------------- -------------- ---------
US East        us-east        Yes
US West        us-west        Yes
EU West        eu-west        Yes
Asia Pacific   ap-south       Yes
Asia Pacific   ap-southeast   Yes
Asia Pacific   ap-northeast   Yes
```
```
NAME (6)                      SLUG           ENABLED
----------------------------- -------------- ---------
US East - Northern Virginia   us-east        Yes
US West - Oregon              us-west        Yes
EU West - Dublin              eu-west        Yes
Asia Pacific - Mumbai         ap-south       Yes …
```
> Add locations to region output.

- script/release.sh
Versions of `goreleaser` before https://github.com/goreleaser/goreleaser/pull/2407/files#diff-42bf43059238f9a44ded247b8c54c94a832da6fd89c2398b44682026b92a0e70L122 created Homebrew Taps that are invalid on M1 Macs, as they don't add the proper conditionals.
This means that the current `pscale` install on M1 Macs does not work.
> Bump `goreleaser` version to support ARM macs properly

- .goreleaser.yml
- README.md
This PR includes the support for https://scoop.sh/, which allows Windows users to install `pscale` in an easy way (similar to macOS Homebrew).
We created the appropriate https://github.com/planetscale/scoop-bucket repository which holds the scoop related manifests (similar to https://github.com/planetscale/homebrew-tap for macOS).
Once we merge this PR and release a new version of the CLI, Windows users will be able to install via the following commands:
```
scoop bucket add pscale https://github.com/planetscale/scoop-bucket.git
scoop install pscale
```
> releases: add `scoop` support for Windows users

- README.md
* example how to create a shell alias pscale that runs pscale from latest docker image
* supports port forwarding and reading/writing to local PlanetScale configuration/auth files
* needs to have $HOME/.config/planetscale folder pre-created so that it can be properly mounted by docker image
* added pointer to more advanced shell function
> Provide example how to run pscale from docker

- internal/cmd/connect/connect.go
- internal/update/update.go
This pull request checks if a branch is ready before connecting to it via the `pscale connect` command. It also fixes a linting error that was introduced in #440
> Check if branch is ready before connecting

- internal/cmd/root.go
- internal/cmd/token/token.go
- internal/config/config.go
Before, we were showing the ID of a service token as a name, when in reality, we should just keep it as the `ID` in the output. This makes a couple of changes. First, it changes the header for a service token to be `ID` instead of `Name`. Secondly, it changes the flag to be `--service-token-id` instead of `--service-token-name`, with the last one being deprecated and hidden. Users will get warned when using the deprecated flag to use the new format, so this gives our users ample time to switch over.
> Switch service token name to be service token ID

- docker/Dockerfile.licensed
The root of this issue is actually that `gem install licensed` tries to install `nokogiri-1.13.1` which doesn't support Ruby 2.5, which is the version of Ruby that comes with `buster`:
```
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]
Debian GNU/Linux 10 \n \l
```
This fails with a cryptic error: 
```
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
--
  | bad response Forbidden 403 (https://api.rubygems.org/quick/Marshal.4.8/nokogiri-1.13.1-x64-unknown.gemspec.rz)
```
This just bumps us to using `bullseye`, which installs a newer version of Ruby, which should work. 
ref https://github.com/sparklemotion/nokogiri/issues/2415
> bump licensed container to use bullseye

- go.mod
- go.sum
- internal/cmd/password/create.go
- internal/cmd/password/create_test.go
- internal/cmd/password/password.go
This doesn't work for everyone yet, only for users who've been flagged in to the ACLs feature.
``` bash
pscale password create aclstest main read-only-password --role reader
Password read-only-password was successfully created in aclstest/main.
Please save the values below as they will not be shown again
NAME                 BRANCH   USERNAME       ACCESS HOST URL                     ROLE     ROLE DESCRIPTION   PASSWORD
-------------------- -------- -------------- ----------------------------------- -------- ------------------ -------------------------------------------------------
read-only-password   main     x3koc4nh3scq   66ve87c9rsvw.us-east-2.psdb.cloud   reader   Can Read            pscale_pw_no_idea
```
> Add role parameter to Password Create

- go.mod
- go.sum
- internal/cmd/connect/connect.go
- internal/cmd/database/dump.go
- internal/cmd/database/restore.go
- internal/cmd/password/create.go
- internal/cmd/password/create_test.go
- internal/cmd/password/password.go
- internal/cmd/shell/shell.go
- internal/cmdutil/cmdutil.go
- internal/proxyutil/remotesource.go
This PR adds a `--role` parameter as a hidden flag to the `pscale shell` and `pscale connect` commands. 
We can now prevent accidental inserts & deletes from a database when using shell for read only queries.
``` bash
go run cmd/pscale/main.go shell  withacls main --org phani --role reader
withacls/main> show tables;
+--------------------+
| Tables_in_withacls |
+--------------------+
| Customers          |
+--------------------+
withacls/main> select count(*) from Customers;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
withacls/main> Insert into Customers(ID) values (12);
ERROR 1045 (28000): target: withacls.-.primary: vttablet: rpc error: code = PermissionDenied desc = Insert command denied to user 'planetscale-reader' for table 'Customers' (ACL check error) …
```
> Add `role` parameter to shell & connect commands

- README.md
:wave: there! bin creator here and long time planetscale fan. 
Just adding another convenient way to manually keep your `pscale` CLI updated in all platforms. Been using this approach for quite some time and I find it extremely convenient. 
Hopefully you find this interesting enough to get it merged :crossed_fingers:
> Add bin install instructions

- internal/cmd/password/create.go
- internal/cmd/password/create_test.go
The docstring says we provide a default, but we don't actually provide a default. Let's do that.
> password/create: specify a default role

- internal/config/config.go
In order to use authentication with a Service Token, you have to pass both the Token ID and the Token. If you also have a local session as a user, it will fall back to using that if you pass one of the two.
Instead, we should error if you've passed one or the other, which is significantly less confusing.
> Error when half of a service token is passed

- cmd/pscale/main.go
Signed-off-by: Matt Layher <mdlayher@planetscale.com>
According to https://pkg.go.dev/os/signal#hdr-Types_of_signals and https://staticcheck.io/docs/checks/#SA1016, os.Kill cannot be caught. staticcheck should catch this but I'm unsure why it is not at the moment. I'll follow up later on.
/cc @dominikh
> cmd/pscale: os.Kill cannot be caught

- internal/auth/authenticator.go
- internal/auth/authenticator_test.go
Signed-off-by: Matt Layher <mdlayher@planetscale.com>
The test setup function wasn't doing much and we can simplify things by putting the mux and server construction right in the test. Also remove the uses of t.Fatal in goroutines and replace with panics, which should ultimately result in HTTP 500s anyway.
> internal/auth: simplify HTTP test construction, panic in handlers

- .gitignore
- internal/auth/authenticator.go
- internal/auth/authenticator_test.go
Signed-off-by: Matt Layher <mdlayher@planetscale.com>
While looking at this on stream, we discovered that the existing test fixtures appeared to be incorrect. The server does accept properly URL-encoded POST form bodies as are now provided when we ultimately encode the `url.Values` maps.
I've built a local copy of `pscale` and can confirm that `pscale auth login` continues to work with the new request format.
I do think we should follow up on the auth server side to check out what sort of logic is being used to decode these requests, so we can verify that all possible inputs are covered by tests.
/cc @iheanyi @fatih
> internal/auth: construct form-encoded bodies with url.Values

- internal/cmd/branch/create.go
A common frustration with new branches is that it's not ready yet. The `pscale branch create` command creates a new branch immediately however it takes time until the branch is `ready`. This confusion leads to various issues, where the users think they can connect to the DB, but it's not possible yet.
We add a new `--wait` flag that blocks on a `pscale branch create` command. It's backwards compatible and people can decide whether they want to wait until the Branch is ready, or they want to create branches without a wait (and do other things meanwhile with the CLI) 
```
$ pscale branch create testdb test-branch --wait
⠧ Waiting until branch test-branch is ready...
```
```
$ pscale branch create testdb test-branch --wait
Branch test-branch was successfully created.
View this branch in the …
```
> cmd/branch: wait until new branch is ready

- internal/cmd/dataimports/lint.go
- internal/cmd/dataimports/lint_test.go
- internal/cmd/dataimports/start.go
- internal/cmd/dataimports/start_test.go
- internal/cmdutil/cmdutil.go
Adds `ssl-mode` to `Lint` and `Start` command in the Imports sub-command.
``` bash
go run cmd/pscale/main.go data-imports lint --help | grep ssl
--ssl-mode string   SSL verification mode, allowed values : disabled, preferred, required, verify_ca, verify_identity
go run cmd/pscale/main.go data-imports start --help | grep ssl
--ssl-mode string   SSL verification mode, allowed values : disabled, preferred, required, verify_ca, verify_identity
```
> Add ssl-mode to imports support

- go.mod
- go.sum
- internal/cmd/deployrequest/dr.go
- internal/cmd/deployrequest/revert.go
- internal/cmd/deployrequest/revert_test.go
- internal/cmd/deployrequest/skiprevert.go
- internal/cmd/deployrequest/skiprevert_test.go
- internal/mock/dr.go
Closes: https://github.com/planetscale/cli/issues/480
This PR adds the following commands to help with reverting a completed deploy request and skipping a pending deploy request revert.
```shell
pscale deploy-request revert <database> <number> [flags]
```
```shell
pscale deploy-request skip-revert <database> <number> [flags]
```
> Add revert deploy requests command

- Makefile
We need to pass this through to the `goreleaser` Docker container so it can publish to GitHub.
> Pass through github token for release

- Makefile
Needed for `goreleaser` to log into Docker.
> Pass through Docker credentials

- go.mod
- go.sum
This pull request includes the update to `sql-proxy` which removes the wrapped error for better error messages when we encounter them client-side.
> Update sql-proxy to `v0.13.0`

- .goreleaser.yml
- Dockerfile
- Makefile
Generates paths independent from the build location.
> Enable -trimpath for all builds

- internal/cmd/connect/connect.go
- internal/cmd/password/create.go
- internal/cmd/shell/shell.go
Now that we've shipped ACLs, we can show this flag in help documents.
> Show `--role` flag on password create, connect & shell commands

- internal/cmd/database/restore.go
The `pscale database dump` commands stores the schema for each table to restore with a `CREATE TABLE` statement. It does not attempt to drop that table before restoring (which is how commands like `mysqldump` work), which means that new branches won't restore because they already contain the table structure.
This (non-default) option will have the restore command issue a `DROP TABLE IF NOT EXISTS` before restoring, which should fix this.
Tested this on one of my databases and it worked like a charm.
> Add an `overwrite` option to restore-dump

- go.mod
- go.sum
- internal/cmd/password/password.go
Depends on https://github.com/planetscale/planetscale-go/pull/136
We're showing the ID as the username and this isn't ideal going forward.
> fix username for generated password

- internal/cmdutil/cmdutil.go
- internal/config/config.go
We don't tell the user what's wrong if their service tokens are missing or if the service tokens are not set, but they forgot to authenticate via access tokens.
With service tokens misconfigured:
```
$ PLANETSCALE_SERVICE_TOKEN_ID="" PLANETSCALE_SERVICE_TOKEN="bar" go run cmd/pscale/main.go connect planetscale main
Error: not authenticated yet. Please run 'pscale auth login'
Error: both --service-token and --service-token-id are required for service token authentication
exit status 2
```
No service tokens are configured, access token is also missing :
```
$ go run cmd/pscale/main.go connect planetscale main
Error: not authenticated yet. Please run 'pscale auth login'
Error: --access-token is required for access token authentication
```
> auth: report better error messages

- internal/cmd/deployrequest/deploy.go
Similar to https://github.com/planetscale/cli/pull/510, this PR adds a
new `--wait` flag that blocks the `dr deploy` subcommand. This allows
the user to wait on this command and makes scripting easier as they can
chain commands without polling the deployment action's status.
fixes: https://github.com/planetscale/cli/issues/518
> dr: add `--wait` flag to `deploy-request deploy` subcommand

- Makefile
- script/release.sh
goreleaser-cross now requires docker creds provided in a JSON file.
We could also add a new CI job that runs on non-main branches that execs goreleaser with the `--snapshot` flag. That will run goreleaser but not publish a release. I've found this helpful on other projects since goreleaser has a tendency to change config options frequently. I added the `GORELEASER_EXTRA_ARGS` to help facilitate this with local testing
> fix(ci): update docker creds for latest goreleaser-cross

- script/release.sh
followup to #571, attempting to figure out new way to pass docker registry creds
This might be the correct addr judging from the prior upstream docs - https://github.com/goreleaser/goreleaser-cross/commit/6ee68a94f140791df2bfea54f91a1529a0d106d9
> fix(ci): try hub.docker.io for registry addr

- script/release.sh
This should be similar to the previous method of authenticating that did not provide a $registry addr: https://github.com/goreleaser/goreleaser-cross/commit/b5b9b7cccea89d31d07ebe4113b4991536c229ed
> fix(ci): try empty string for docker hub addr

- internal/cmd/database/dump.go
- internal/cmd/database/restore.go
- internal/dumper/dumper.go
This allows a user to pick the number of threads to use when dumping and restoring. Defaults are unchanged for dump, but are set low (1) for restoring, to ensure that we don't overwhelm a small database. Users can configure that to be higher if they happen to want higher concurrency.
```
$ pscale db restore-dump --help
Restore your database from a local dump directory
Usage:
pscale database restore-dump <database> <branch> [options] [flags]
Flags:
--dir string          Directory containing the files to be used for the restore (required)
-h, --help                help for restore-dump
--local-addr string   Local address to bind and listen for connections. By default the proxy binds to 127.0.0.1 with a random port.
--overwrite-tables    If true, will attempt to DROP TABLE before restoring. …
```
> dump/restore: set number of threads to be configurable

- Dockerfile
- Makefile
- docker-compose.yml
- docker/Dockerfile.licensed
Depends on https://github.com/goreleaser/goreleaser-cross/pull/18 to be released first so we have a new `goreleaser-cross` base image.
> Update to latest Go 1.19.4

- Brewfile.lock.json
- go.mod
- go.sum
- internal/cmd/token/showaccess_test.go
- internal/cmd/token/token.go
This PR updates the `pscale service-token show-access` cmd with a new format:
```
➜  cli git:(frances/fix-service-tokens) ✗ go run ./cmd/pscale/main.go service-token show-access irc25xa5f5hk --api-url http://api.pscaledev.com:3000
!! WARNING: You are using a self-compiled binary which is not officially supported.
!! To dismiss this warning, set PSCALE_DISABLE_DEV_WARNING=true
RESOURCE NAME   RESOURCE TYPE   ACCESSES
--------------- --------------- ---------------------------------------------------------
test            Database        restore_branch_backup, restore_production_branch_backup
```
This should fix: https://github.com/planetscale/surfaces/issues/912
> [service-tokens] Update show access with new format

- internal/cmd/token/addaccess.go
The token access list on the main docs site was often out of date. We should refer to the automated list in the API docs instead.
I've already updated original page to point to the API docs.
> Refer to service token grant list in the API docs

- Dockerfile
- Makefile
- docker-compose.yml
- docker/Dockerfile.licensed
Latest and greatest that also fixes some upstream CVEs.
> Update to Go 1.20.1

- Makefile
- docker/Dockerfile.goreleaser
This is so that we can produce SBOMs as part of the release process.
> Add `syft` to goreleaser container

- internal/cmd/branch/safe_migrations.go
Now that this is released, we can make this CLI command visible.
> Remove hidden flag from safe migrations command.

- go.mod
- go.sum
- internal/cmd/dataimports/lint.go
- internal/cmd/dataimports/start.go
Help documents for `lint` and `start` commands  for data imports:
Needs https://github.com/planetscale/planetscale-go/pull/160 
``` bash
./pcli data-imports lint -h
lint external database for compatibility with PlanetScale
Usage:
pscale data-imports lint [options] [flags]
Aliases:
lint, l
Flags:
--database string                    Name of the external database
-h, --help                               help for lint
--host string                        Host name of the external database.
--password string                    Password to connect to external database.
--port int                           Port number to connect to external database (default 3306)
--ssl-certificate-authority string   Provide the full CA certificate chain here
--ssl-client-certificate string      Client …
```
> Add CLI parameters for region, ssl authentication to data imports.

- internal/cmd/connect/connect.go
Fixes: https://github.com/planetscale/cli/issues/500
**Before:**
```
pscale connect mike
Error: Not found
```
**After:**
```
pscale connect mike
Error: database mike does not exist in organization mike
```
> Improve error message when connecting to not found DB

- internal/cmd/branch/switch.go
Fixes: https://github.com/planetscale/cli/issues/607
**Before:**
```
Error: internal error, response body doesn't match error type signature
```
**After:**
```
Error: the access token has expired. Please run 'pscale auth login'
```
> Fix error handling for `switch` command

- internal/cmd/database/list.go
Fixes: https://github.com/planetscale/cli/issues/556
Improves the error message for cases where the user doesn't have permission to access it.
We can't get more specific than this since we do not give more detailed info via the API.
> Improve error message for `db list` when org missing or not authed

- internal/dumper/dumper.go
Fixes: https://github.com/planetscale/cli/issues/515
This updates `dump` to exclude dumping any vitess ghost tables.
> Exclude vitess ghost tables from dump command

- internal/cmd/shell/shell.go
Fixes: https://github.com/planetscale/cli/issues/453
When a user has `~/.my.cnf` configured with a database name. For example:
```
[client]
database=databasename
```
pscale shell errors with the following:
```
ERROR 1105 (HY000): unknown database 'databasename'
```
This is easily fixed by passing the database name.
> Shell: fix conflict with DB name

- internal/config/config.go
The switch to using Keychain reordered some of the token creation code, which means that we tried to write the token before we tried to make the folder. This adds code in that codepath as well to look at the `filepath.Dir` we're trying to write that token to, and does an `os.MkdirAll`. 
This should work fine with the rest of the codebase, as this is all atomic and only done once. 
Fixes: https://github.com/planetscale/cli/issues/667
> Attempt `os.MkdirAll` for the config-file if we fallback from Keychain

- internal/dumper/dumper.go
- internal/dumper/dumper_test.go
Fixes: https://github.com/planetscale/cli/issues/652
Fixes: https://github.com/planetscale/cli/issues/645
Originally, the dump command grabbed the column names by running `select *`.
This does not work with invisible columns, since `select *` will only return visible columns.
This PR updates `dump` to use `SHOW FIELDS` which returns invisible columns.
```
invisible/main> show fields from mike;
+-------+------+------+-----+---------+-----------+
| Field | Type | Null | Key | Default | Extra     |
+-------+------+------+-----+---------+-----------+
| id    | int  | NO   | PRI | NULL    |           |
| test  | int  | YES  |     | NULL    | INVISIBLE |
+-------+------+------+-----+---------+-----------+
```
We then use that list to generate the dump.
> Dump: support invisible columns

- go.mod
- go.sum
- internal/cmd/database/create.go
- internal/cmd/database/create_test.go
This PR adds a confirmation dialog when a user creates a database and there are no more free databases available in the organization, creating a scaler database. 
``` bash
$ pscale database create paid-database --org Phani
Organization [phani] does not have any free databases remaining.
If you choose to continue, this  database will be created on Scaler plan. The monthly cost is $29.
? Please type $29 to confirm:
```
> Confirm when creating Scaler databases

- go.mod
- go.sum
- internal/cmd/shell/shell.go
Closes: https://github.com/planetscale/cli/issues/429
This updates the CLI to use XDG_DATA_HOME for the location of the users shell history file.
The [xdg package](https://github.com/adrg/xdg) takes care of returning the path based on the operating system and creating the directory if it is not present.
For anyone with an existing `~/.pscale/history` directory, it will continue to use it. To avoid wiping out all of a person's history
> Respect users XDG directory setting for history file

- internal/cmd/database/dump.go
Fixes #679.
Currently `planetscale database dump <database>` defaults to only dumping from the `<database>`  keyspace. 
Some database have multiple keyspaces, and users want to be able to dump those. This PR preserves the current behavior, but lets users optionally choose a different keyspace with `--keyspace`.
> dump: support --keyspace

- internal/cmd/dataimports/lint.go
The `data-imports lint` command accepts ssl cert info, but was overwriting `sslKey` with the client cert.
> Change ssl client certificate to set correct flag

- internal/cmd/branch/switch.go
Before:
```
✘-2 ~/src/github.com/planetscale/cli [main|✔] 
08:57 $ pscale branch switch --database planetscale main
!! WARNING: You are using a self-compiled binary which is not officially supported.
!! To dismiss this warning, set PSCALE_DISABLE_DEV_WARNING=true
Finding branch main on database planetscale
Successfully switched to branch main on database planetscale✔ ~/src/github.com/planetscale/cli [main|…1]
```
After:
```
✔ ~/src/github.com/planetscale/cli [main|✚ 1…1] 
08:58 $ pscale branch switch --database planetscale main
!! WARNING: You are using a self-compiled binary which is not officially supported.
!! To dismiss this warning, set PSCALE_DISABLE_DEV_WARNING=true
Finding branch main on database planetscale
Successfully switched to branch main on database planetscale
✔ …
```
> cmd/branch: print newline after switching branches

- Makefile
- internal/cmd/branch/lint.go
This struct tag syntax is invalid. Run vet in CI to prevent future issues.
> cmd/branch: fix vet issue, run vet in make

- internal/cmd/branch/diff.go
- internal/cmd/branch/schema.go
- internal/cmd/deployrequest/diff.go
- internal/cmd/root.go
- internal/cmd/shell/shell.go
- internal/printer/printer.go
Half of these methods don't return errors and were cargo culted. For the others, you can just explicitly ignore the error to more clearly indicate you don't care.
> internal: remove unneeded errcheck annotations

- internal/dumper/loader.go
For https://github.com/planetscale/cli/issues/697. All slice index accesses must have a bounds check beforehand.
> internal/dumper: fix restore panic

- go.mod
- go.sum
- internal/cmd/api/api.go
- internal/cmd/api/api_test.go
- internal/cmd/root.go
- internal/config/config.go
`pscale api ...` makes it easy to write API requests in scripts without having to use `curl` and manage reading credentials from the environment.
```
$ pscale api --help
Performs authenticated calls against the PlanetScale API and prints the response to stdout.
ENDPOINT
The endpoint should be a path for the v1 PlanetScale API, not including the "v1" prefix. The placeholder "{org}",
"{db}" and "{branch}" will be replaced with the currently selected organization, and the project's database and
branch. If invoked from outside a project, "{db}" and "{branch}" yield an empty string.
Query parameters, such as for pagination, can be added with the --query/-Q flag, in "key=value" format.
By default, all HTTP requests use the GET method, unless fields for the body are passed via --field/-F, in …
```
> cmd/api: a command to write authenticated API requests

- go.mod
- go.sum
- internal/cmd/deployrequest/show.go
- internal/cmd/deployrequest/show_test.go
For: https://github.com/planetscale/cli/issues/702
When automating workflows, we don't always have the DR number. This allows us to lookup a DR by the `branch` name (head branch).
> Add ability to `deploy-request show` by branch name

- internal/cmd/deployrequest/deploy.go
- internal/cmd/deployrequest/deploy_test.go
- internal/cmd/deployrequest/show.go
- internal/cmdutil/cmdutil.go
Closes: https://github.com/planetscale/cli/issues/702
Allows targeting an open DR by the head branch name. Making it easier to script deploy requests without needing to know the DR number.
> Add ability to deploy DR by branch name

- internal/cmd/deployrequest/create.go
- internal/cmd/deployrequest/create_test.go
Closes: https://github.com/planetscale/cli/issues/696
Also, removed the deprecated "deploy-to" field. It has been deprecated for 6 months. 
```diff
Usage:
pscale deploy-request create <database> <branch> [flags]
Flags:
-h, --help           help for create
--into string    Branch to deploy into. By default, it's the parent branch (if present) or the database's default branch.
+     --notes string   Notes to include with the deploy request.
```
> Add ability to set notes when creating a deploy request

- internal/cmd/connect/connect.go
This pull request adds a flag to let the connect command fail loudly and not pick a random port.
Closes https://github.com/planetscale/cli/issues/713
> Allow connect to fail loudly

- internal/cmd/branch/switch.go
Not every user has a default of `main` for their default branch. This pull request leaves this value to be explicitly blank, the API will then branch from whatever the default branch is anyways, so the user doesn't have to type it every time.
> Default to empty string for `parent-branch` for `branch switch`

- internal/cmd/branch/safe_migrations.go
Given that we had two variables named `err` but in two different scopes, our `err` variable was getting shadowed by the call to `LintSchema`, so it'd return an empty error. This pull request changes the variable names so the shadowing isn't a problem anymore.
Fixes https://github.com/planetscale/cli/issues/720
> Fix error handling for enabling safe migrations

- internal/cmd/password/delete.go
- internal/cmd/password/delete_test.go
Following the previous `password delete` subcmd's instruction, I misunderstood that I should pass the password's name instead of its ID, but actually that was wrong. The reason why I did such misoperation is I can only see the password's name on the web UI.
So this patch emphasizes the intention of receiving the password's ID on the subcmd in the usage description.
> Revise the phrasing of `password delete` subcmd usage to place greater emphasis on the intention of receiving a password ID

- Makefile
```
Flag --rm-dist has been deprecated, please use --clean instead
```
> Fix deprecation in release script

- internal/cmd/database/dump.go
Fixes: https://github.com/planetscale/cli/issues/732
To prevent conflicts when running dump multiple times.
Example dir name now: `pscale_dump_mydatabase_mybranch_mydb_20231031_153010`
> Add current timestamp to pscale dump

- internal/cmd/branch/switch.go
The --org flag is already defined for all `branch` commands.
I found that being defined twice (in branch and in switch) was causing it to be ignored.
Fixes: https://github.com/planetscale/cli/issues/684
> Fix: branch switch ignoring --org flag

- internal/cmd/database/dump.go
> database/dump: port to using psdbproxy

- internal/cmd/database/restore.go
> database/restore: port to using psdbproxy

- Dockerfile
Adding ssh to the dockerfile since go-releaser needs it to publish to aur.
> Add ssh to docker for aur publish

- docker/Dockerfile.goreleaser
There are 2 goreleaser dockerfiles, this is the one used in the build
> Adding ssh to goreleaser dockerfile

- .goreleaser.yml
- fix(AUR): install location for source completions
Also changes nfpms completions folder to `bash-completions`, see
https://unix.stackexchange.com/a/605051 for details on why.
> Fix(AUR) install location for source completions

- Dockerfile.goreleaser
Removes the `Dockerfile.goreleaser` file from the root directory because the source of truth exists in `docker/Dockerfile.goreleaser`.
> Remove root directory Dockerfile for goreleaser.

- Dockerfile
- docker/Dockerfile.goreleaser
See https://go.dev/doc/devel/release#go1.21.5 for more details.
> Bump to go1.21.5

- internal/cmd/token/deleteaccess.go
- internal/cmd/token/deleteaccess_test.go
Follow up to: https://github.com/planetscale/cli/pull/783
This enables `delete-access` to work for org level permissions.
Now by leaving `--database` off, it will send a delete request for org level token access.
```
➜  cli git:(main) ✗ go run cmd/pscale/main.go service-token delete-access n8in8gt1j23g create_databases delete_databases
create_databases, delete_databases have been removed.
```
> service-token delete-access for Orgs

- internal/cmd/ping/ping.go
Make `--provider` match the help text style of the top-level `--format` flag. Use periods consistently.
```
✔ ~/src/github.com/planetscale/cli/cmd/pscale [main|✚ 1] 
14:09 $ pscale ping --help
Ping public PlanetScale database endpoints
Usage:
pscale ping [flags]
Flags:
--concurrency uint8   Number of concurrent pings. (default 8)
-n, --count uint8         Number of total pings. (default 10)
-h, --help                help for ping
-p, --provider string     Only ping endpoints for the specified infrastructure provider. Possible values: [aws, gcp]
--timeout duration    Timeout for each ping to succeed. (default 5s)
Global Flags:
--api-token string          The API token to use for authenticating against the PlanetScale API.
--api-url string            The base URL for the PlanetScale API. …
```
> internal/cmd/ping: CLI help and completion improvements

- internal/cmd/root.go
- internal/update/update.go
- internal/update/update_test.go
I got the following message while testing my `pscale ping` changes:
```                                                                                                                                                                                       
Updater error: &errors.errorString{s:"skipping update, error: Malformed version: "} 
```
The `%#v` is not particularly human-friendly so remove that. In addition, the version parsing library returns a less than helpful error `Malformed version: ` with empty string, so double check the error return when using a self-compiled binary.
If self-compiled, do not update. Users already get a banner for self-compiled binaries so they shouldn't expect updates to work either.
> internal/update: don't error with no build version

- internal/cmd/shell/shell.go
If we explicitly pass the database name when connecting to Vitess, we bypass Vitess' transparent query routing capabilities when dealing with multiple keyspaces.
Using `@primary` instead of an explicit keyspace name will allow us to query transparently across all keyspaces as soon as `pscale shell` connects.
> Replace database name with @primary

- internal/update/update.go
- internal/update/update_test.go
The previous version of this code that I replaced threw away the error when it couldn't write the state file, resulting in errors such as the following being ignored:
```
open /home/runner/.config/planetscale/state.yml: no such file or directory
```
The likely problem here is that the state file exists in nested directories that may not exist when the state entry is written. Ensure the parent directories exist and have reasonable permissions to enable walking them.
Relax the permissions on the state file to `0o644`; there's nothing sensitive in here so making it group and world-readable is totally fine.
For https://github.com/planetscale/setup-pscale-action/issues/8. /cc @mscoutermarsh
> internal/update: create parent directories for state file

- internal/update/update_test.go
I had a slight variation of this before but removed it due to an unexpected actions failure. This should cover our bases so we can report something useful.
> internal/update: remove test error field

- internal/cmd/root.go
- internal/update/update.go
- internal/update/update_test.go
There is no reason to check for updates in CI environments such as Buildkite or GitHub actions. /cc @nickvanw
> internal/update: add Enabled with CI check

- internal/cmd/database/create.go
This is no longer needed because the API does not auto create a scaler DB anymore without the plan explicitly being passed.
Now if a user does not pass a plan, it will default to free. If they are out of free DBs, they'll get a message back.
> Remove plan confirmation on database create

- go.mod
- go.sum
- internal/cmd/password/list.go
- internal/cmd/password/password.go
- internal/mock/password.go
This adds two new columns to the password list, "TTL REMAINING", and "EXPIRED".
This allows a user to see, if they have a credential that is ephemeral, to see how long it has left before it's expired, and if it is expired already.
Relies on https://github.com/planetscale/planetscale-go/pull/193
After creating with a 60s TTL:
```
$ ./pscale password list mattdb
ID             NAME                     BRANCH   USERNAME               ROLE     ROLE DESCRIPTION               TTL   TTL REMAINING   EXPIRED
-------------- ------------------------ -------- ---------------------- -------- ------------------------------ ----- --------------- ---------
zxc6td6uu0rh   test-ttl                 main     amzdunhtul1jou6yd11r   reader   Can Read                        60              57   No
oddkvx4zj8y9 …
```
> cmd/password/list: show TTL remaining and if password is expired

- internal/cmd/database/dump.go
- internal/cmd/database/restore.go
- internal/cmd/shell/shell.go
- internal/passwordutil/password.go
This then knocks down the TTL for credentials from 6 hours to 5 minutes
+ refreshing every 2.5 minutes.
> passwordutil: implement a basic refresh loop

- internal/cmd/password/create.go
- internal/cmd/password/create_test.go
Go has a native duration type and it's much friendlier than requiring the caller to do integer math. `--ttl 6h`, `--ttl 1h30m`, etc.
To prevent misuse, require the caller to specify _at least_ 1 second as the TTL when the flag is set.
> cmd/password: use a duration for TTL

- internal/cmd/password/create.go
- internal/cmd/password/create_test.go
The Go stdlib doesn't want to support "days" for the reasons linked in the issue, but they're very reasonable for a credential TTL argument such as `--ttl 30d`. Support the absolute basics with no conveniences like `30d12h`.
> cmd/password: extend ttlFlag with d

- Makefile
- docker/Dockerfile.goreleaser
Turns out, these are different releases for goreleaser-cross vs goreleaser, and v1.21.5 is the latest for -cross variant.
> meta: move goreleaser-cross back to v1.21.5

- Dockerfile
- Makefile
- docker-compose.yml
- internal/config/config.go
We don't allow for `--access-token` in our configuration. From what I can tell this error occurs if you haven't yet authenticated with `pscale auth login`. This error message is slightly different than trying to login using tokens.
> Removing --access-token from error message

- Makefile
It's not this, it's that. https://github.com/goreleaser/goreleaser-cross/releases/tag/v1.21.5
> goreleaser: correct version

- internal/cmd/branch/vschema.go
This was hidden, but it doesn't need to be.
> vschema get: show keyspaces param

- internal/cmd/branch/vschema.go
This will hit for more reasons than the branch not existing, let's make that clear.
> Vschema: make error message more clear

- internal/cmd/auth/check.go
Fixes: https://github.com/planetscale/cli/issues/836
`v1/organizations` works for both service tokens and users. If it responds successfully, we are logged in.
> Add an API call to the auth check

- go.mod
- go.sum
- internal/cmd/password/create.go
- internal/cmd/password/create_test.go
- internal/cmd/password/password.go
This PR adds `--replica` flag to create password, which when enabled, will create a password that redirects queries to the replica tablets, or the  branch's read-only-regions, depending on where latency is smallest.
> Add `--replica` flag to create password

- internal/cmd/password/create.go
- internal/cmd/password/create_test.go
This PR makes it so that we default to a `reader` role when passing `--replica`, and not `--role`. 
- The default `admin` for `--replica` flag is set in the `RunE` func instead of the flag definition
- This is so we can differentiate between a user passing no `--role`, and the user intentionally setting `--role=admin`
- If no `--role` is passed, we default it to `reader` if `--replica` is passed, and `admin` if `--replica` is _not_ passed
> Default to `reader` role when passing `--replica` and not `--role`

- internal/cmd/connect/connect.go
- internal/cmd/password/create.go
- internal/cmd/shell/shell.go
- internal/passwordutil/password.go
This pull request implements replica credential creation inside of both the shell and connect commands.
> Add support for replicas in `shell` and `connect` commands

- internal/cmd/connect/connect.go
- internal/cmd/password/create.go
- internal/cmd/shell/shell.go
Removes the `MarkHidden` annotation on the `replica` flag.
> Removes `MarkHidden` on `replica` flag

- cmd/pscale/main.go
- internal/cmd/root.go
- internal/cmd/shell/shell.go
MySQL handles signals like an interrupt (ctrl+c) as a query interrupt / cancelation of the current input. This means it's not expected to have it shut down the CLI.
When we have the MySQL shell active, we should mask any signals and forward them straight to MySQL instead.
This sets up the logic to do so. It means we have to manually set up the initial context and signals instead of using signal.NotifyContext, since we need to be able to later on disable them which means access to the actual channel registed.
So we have to do this work manually and then pass through what we've registed, so we can disable it and setup the proper ones when we invoke the shell.
We also do the work to reverse it all, which is not strictly needed at the moment, but avoids making mistakes with it in the future …
> Fix the MySQL shell signal handling

- internal/cmd/shell/shell.go
- internal/printer/printer.go
If pscale is used in scripts with the explicit
`PSCALE_ALLOW_NONINTERACTIVE_SHELL` env flag, disable the signal changes we do for making the shell work in interactive mode.
This check also needs to verify that all of stdin, stdout & stderr are a proper TTY and not just stdout, since if you pipe in only input for example we still need to disable this since there's no foregrounding.
Fixes #856
> Disable custom signal handling if not on foreground

- internal/cmd/auth/check.go
Fixes a missing newline in the affirmative `pscale auth check` output
Currently:
```sh
bash-3.2$ pscale auth check
You are authenticated.bash-3.2$
```
> Fix postitive auth check message

- internal/cmd/branch/create.go
A fairly common point of confusion is that `pscale branch create --restore` will accept a `--region` flag but will always restore to the region the backup was taken in. That's the correct behavior but it isn't documented properly.
This changes makes those flags mutually exclusive and documents the incompatibility in the app.
```sh
$ pscale branch create beam main --region us-west --restore abc123
Error: if any flags in the group [region restore] are set none of the others can be; [region restore] were all set
```
```sh
$ pscale branch create --help
Create a new branch from a database
...
Flags:
--from string      Branch to be created from
-h, --help             help for create
--region string    Region for the database. Can not be used with --restore
--restore string   Backup to restore …
```
> Make region and restore flags mutually exclusive for branch create

- Makefile
- docker/Dockerfile.goreleaser
We're on an old version of Syft, latest version is 1.9.0.
> Upgrade Syft to latest version.

- Makefile
- docker/Dockerfile.goreleaser
This PR upgrades the `GORELASE_CROSS_VERSION` to 1.22.4. I followed the matrix here to get 1.22.4 and 2.0.0 
https://github.com/goreleaser/goreleaser-cross/pkgs/container/goreleaser-cross/versions?filters%5Bversion_type%5D=tagged
> Upgrade `GORELEASE_CROSS_VERSION`

- .goreleaser.yml
This adds `version: 2` and changes `folder` to `directory` to see if we can get rid of deprecation warnings.
> Goreleaser configuration fixes

- .goreleaser.yml
Publishing build is currently failing like this
```
[2024-07-12T18:37:45Z]   • cataloging artifacts
[2024-07-12T18:37:45Z]     • cataloging                                     cmd=syft artifact=dist/pscale_0.203.0_windows_arm.zip sbom=[pscale_0.203.0_windows_arm.zip.spdx.sbom]
[2024-07-12T18:37:46Z]     • took: 1s
[2024-07-12T18:37:46Z]   ⨯ release failed after 1m43s                       error=cataloging artifacts: command did not write any files, check your configuration
[2024-07-12T18:37:53Z] make: *** [Makefile:59: release] Error 
```
Current syft arguments looks like the old goreleaser defaults:
https://github.com/goreleaser/goreleaser/blob/bfdec808aba208cfdedeb3bef0a16255bf1d87b3/www/docs/customization/sbom.md
We're using a newer version of syft now that has deprecated `--file`, and …
> Fix syft call in goreleaser config

- internal/update/update.go
When the token is invalid is causes the request to fail. Doing more harm than good.
Removing it, since rate limits have not been seen to be an issue for people without it set.
> Do not use github token on update check

- internal/cmd/database/dump.go
- internal/dumper/dumper.go
- internal/dumper/dumper_test.go
- internal/dumper/pool.go
- internal/dumper/pool_test.go
This allows one to pass `--shard` as well as `--keyspace` to support dumping from a single shard.
Note that this does not validate the shard exists; if an invalid keyspace is passed it will not dump any data.
> `pscale database dump`: support shard targeting

- internal/cmd/branch/schema.go
This pull request unhides the keyspace flag for the `branch schema` command so users know that they can pass it in to view a specific keyspace's schema.
> Unhide keyspace flag for `branch schema` command

- .gitignore
- internal/cmd/deployrequest/create.go
- internal/cmd/deployrequest/deploy.go
- internal/cmd/deployrequest/dr.go
This PR adds the `--instant` flag to `pscale deploy-request deploy` that will deploy the deploy request using an instant ddl strategy:
It also adds the `Instant DDL Eligible` field to `pscale deploy-request list` that denotes whether or not the `--instant` flag can be used for deploy:
with the `--wait` flag and `--instant`:
> Add --instant flag for deploying DR

- README.md
Running `brew install mysql-client` today will give you MySQL 9.0's client.
Trying to use `pscale shell` with the MySQL 9 client will produce the `Authentication plugin 'mysql_native_password' cannot be loaded` error shown in  https://github.com/planetscale/discussion/discussions/648
I believe any MySQL 8 client will work so we might as well recommend the latest.
> Documentation: pscale shell requires the mysql 8 client

- internal/cmd/branch/create.go
Marks a couple of additional flags as incompatible with `--restore`.
`--from` seems to be ignored during a restore as the new branch will always have the same parent as the branch the backup was taken from. There's no "from" option when restoring a backup from the web app.
`--seed-data` will always use the latest backup of the parent branch.
> Prevent --from and --seed-data being used with --restore

- internal/dumper/dumper.go
- internal/dumper/loader.go
Currently, when using either the `pscale database dump` or `pscale database restore-dump` commands there may be times where you would like to cancel out of the operation because it is taking too long, a mistake was made, etc.
At the moment the behavior for both commands is not ideal in these cases since you can attempt to send a `Ctrl+C` command but it won't be very responsive / immediate as you expect it to be.
Instead, depending on the length of time the operation has remaining, it may actually continue to completion and/or the renewal of the temporary 5 minute credential won't occur and it will stop / error then.
```console
% pscale database dump <DATABASE> <BRANCH> --org=<ORG> --output="<DUMP_DIRECTORY>"    
Starting to dump all tables from database <DATABASE> to folder …
```
> Added context to longer-running functions for quicker cancellation

- internal/config/config.go
Addresses a situation that can currently occur somewhat easily with the `--service-token-id` and `--service-token` values passed in via the CLI.
If the values are accidentally passed in a swapped manner, then when attempting to run your CLI command a user might receive something like the following error, rather than a more specific error message about the values being swapped:
```
Error: organization <ORG> does not exist or your account is not authorized to access it
```
There are a few ways to handle this situation, such as having a hard error thrown during the `IsAuthenticated()` check to direct users to the issue to automatically swapping the values internally for the user if it is detected they have provided values in the correct format that have simply been swapped.
For this pull …
> Improve service token value input processing

- internal/cmd/connect/connect.go
View the before and after video here: https://screen.studio/share/YVe5yTeO
Updates the `pscale` connect command to support interactive input during execution. Previously, the command couldn’t handle user interactions. By adjusting the standard input configuration in `internal/cmd/connect/connect.go`, this change enables interactive sessions, enhancing the command’s usability.
**Why?**
I was having issues getting DrizzleORM's `push` command working with the new `VECTOR` data type in PlanetScale. It would not work with `drizzle-kit` by normally adding the credentials.
Though, when setting the `dbCredentials` in the Drizzle config to the following and using `pscale connect --execute` it works just fine:
```ts
export default {
schema: './src/db/schema.ts',
out: './drizzle/migrations', …
```
> Allow `pscale connect` to accept interactivity

- internal/cmd/auth/login.go
In https://github.com/planetscale/cli/pull/938 we had the CLI not touch the configuration file if the user was authenticating. This is a good thing to do if the user is re-authenticating to the same user, but they're not always doing that.
If a user switches between two accounts and their new account does not have access to the previously configured organization, the CLI will default to the previous account and fail, appearing broken.
This goes ahead and lists the orgs the user is in - if the previous default is not in the list of orgs the new user is in, it rewrites the config.
> cli: write out new default org if the user cannot see the previous default

- Dockerfile
- Makefile
As documented in https://github.com/planetscale/cli/issues/929 the mysql client package for Apline is actually MariaDB which breaks `pscale shell`. There doesn't seem to a simple way to get the MySQL 8 client installed in Alpine Linux.
```
/ # mysql --version
mysql  Ver 15.1 Distrib 10.11.8-MariaDB, for Linux (x86_64) using readline 5.1
/ # pscale shell beam main --org=jgreet --service-token-id=XXX --service-token=pscale_tkn_XXX
Error: could not parse server version from: mysql  Ver 15.1 Distrib 10.11.8-MariaDB, for Linux (x86_64) using readline 5.1
```
This PR swaps the base image to a current Ubuntu LTS release for an easy MySQL clien install. The tradeoff is it expands the Docker image from 82MB to 204MB. 
```
mysql  Ver 8.0.41-0ubuntu0.24.04.1 for Linux on aarch64 ((Ubuntu))
beam/|⚠ …
```
> Use MySQL 8 client in Docker image instead of MariaDB

- internal/cmd/database/create.go
- internal/cmd/keyspace/create.go
- internal/cmd/keyspace/resize.go
- internal/cmd/root.go
- internal/cmd/size/cluster.go
- internal/cmd/size/cluster_test.go
- internal/cmd/size/size.go
- internal/cmdutil/completions.go
- internal/testutil/common.go
This pull request adds a `size` command for us to list sizes of various resources within PlanetScale. The first component that we implemented was cluster sizing, so a user can get a list of all sizes using `pscale size  cluster list` and get all of the valid sizes. This can be used in tandem with the database or keyspace creation flow in order for the users to know what the valid inputs are.
> Add `size` command for listing sizes

- internal/cmd/size/cluster.go
- internal/cmdutil/completions.go
This needs to be pluralized. Also, removes the sorting function because we now always return the SKUs in the sorted order.
> Pluralize vCPU

- internal/cmd/workflow/reverse_traffic.go
- internal/cmd/workflow/reverse_traffic_test.go
- internal/cmd/workflow/workflow.go
As part of #999, we want to implement the `reverse-traffic` command for reversing traffic back to the source keyspace.
> Implement `reverse-traffic` command

- go.mod
- go.sum
- internal/cmd/database/create.go
- internal/cmd/keyspace/create.go
- internal/cmd/keyspace/keyspace.go
- internal/cmd/keyspace/resize.go
- internal/cmd/keyspace/resize_test.go
- internal/cmd/size/cluster.go
- internal/cmd/size/cluster_test.go
- internal/cmdutil/completions.go
This pull request updates the cluster JSON fields to use `cluster_name` instead of `cluster_rate_name`. Additionally, we now have support for dasherized cluster names in the API, so we can use that everywhere since it looks cleaner.
> Update cluster sizing to use updated names

- internal/cmd/workflow/cancel.go
- internal/cmd/workflow/complete.go
- internal/cmd/workflow/create.go
- internal/cmd/workflow/cutover.go
- internal/cmd/workflow/retry.go
- internal/cmd/workflow/reverse_cutover.go
- internal/cmd/workflow/reverse_traffic.go
- internal/cmd/workflow/switch_traffic.go
- internal/cmd/workflow/verify_data.go
- internal/printer/printer.go
This pull request changes the workflow output messages to use the number instead of the name in workflow commands, since that's the primary identifier we use in the CLI commands.
> Use number instead of name for the workflow messages

- internal/cmd/database/restore.go
This can be configured higher, this is the default.
> Max query size: clarify in help message

- go.mod
- go.sum
- internal/cmd/backup/restore.go
- internal/cmd/backup/restore_test.go
- internal/cmd/branch/create.go
- internal/cmd/branch/create_test.go
- internal/cmd/database/create.go
This pull request adds the `--cluster-size`  flag to the `branch create` and `backup restore` commands. This flag is required if and only if you are restoring from a backup and is not useful otherwise.
> Add `cluster-size` to backup restoration commands

- internal/cmd/branch/create.go
The not_found response doesn't specify if it was the database or branch that wasn't found so we shouldn't assume it was the database in the user facing error message.
Fixes #954, https://github.com/planetscale/discussion/discussions/655
> Fix error message when branching from branch that doesn't exist

- internal/cmd/mcp/server_handlers.go
- internal/cmd/mcp/server_helpers.go
Use cmdutil.HandleError for better error messages from the MCP server.
Example when using the MCP server with an expired auth token:
Before:
```
Error executing MCP tool:
MCP error -32603: failed to list databases: internal error, response body doesn't match error type signature
```
After:
```
Error executing MCP tool:
MCP error -32603: the access token has expired. Please run 'pscale auth login'
```
> mcp: improve error messages

- internal/cmd/branch/create.go
- internal/cmd/branch/create_test.go
This removes the requirement for using `cluster-size` and `restore` together that was added in #1023.  It'll default to a `PS-10` if it isn't specified. 
Fixes https://github.com/planetscale/cli/issues/1029
> Remove requirement for cluster-size flag

- internal/cmd/api/api.go
- internal/cmd/api/api_test.go
Requests like `pscale api /organizations/$org/databases/$db/branches/$branch/query-patterns` get redirected to an S3 bearer URL.  `pscale api` follows those redirects.  It needs to not include the `Authorization` header when talking to S3, because including that header is a security leak, and also causes S3 to reject the request.
The fix is to teach the OAuth2 http client to not follow redirects that go to a new root domain (e.g., somewhere other than planetscale.com).  Instead of following the redirect automatically in the OAuth2 http client, now we construct a new, clean http client without the Authorization header.
This PR fixes a security leak, in which a client's OAuth2 bearer token would be forwarded to S3.  That's probably harmless: it was https, and there's no reason to think S3 …
> Fix API redirects

- internal/cmd/shell/shell.go
Point people in the right direction if they try to pipe a file in to `pscale shell`
> More helpful error for non-interactive shell

- internal/cmd/mcp/server.go
- internal/cmd/mcp/server_handlers.go
This extends `pscale mcp server` to include a new tool, `get_insights`.  `get_insights` lists the top queries for a given database branch by five metrics: total time, total rows read, rows read per row returned, p99 latency, and rows affected.
> Add a `get_insights` MCP tool

- internal/cmd/api/api.go
- internal/cmd/branch/create.go
I'm not sure why but the backticks change the description of the `-cluster-size` flag in a confusing way.
On 0.241.0 
```
$ pscale branch create
Error: missing arguments <source-database, branch>
Usage:
pscale branch create <source-database> <branch> [options] [flags]
Aliases:
create, b
Flags:
--cluster-size pscale size cluster list   Cluster size for branches being created from a backup or seeded with data. Use pscale size cluster list to see the valid sizes. (default "PS-10")
--from string                             Parent branch to create the new branch from. Cannot be used with --restore
...
```
> Fix branch create help message

- internal/cmd/auth/login.go
This should make it more obvious when https://github.com/planetscale/cli/issues/1058 happens.
> Config: Return a better error if we can't write the config file

- Dockerfile.goreleaser
Closes https://github.com/planetscale/cli/issues/929
We were bundling MariaDB instead with alpine, which is less than stellar.
> use ubuntu-based image for goreleaser

- internal/cmd/mcp/server_helpers.go
Closes https://github.com/planetscale/cli/issues/1052
This requires that all branches used have a replica, which won't always be the case for dev branches. For now, we can send them to the primary.
> MCP server_helpers.go: don't hardcode a replica

- internal/cmd/auth/check.go
Currently `auth check` only works for user auth. This fixes it to work for both service tokens and user auth.
> Fixes `auth check` for service tokens

- internal/cmd/branch/create.go
- internal/cmd/branch/create_test.go
- internal/cmd/branch/show.go
- internal/cmd/branch/show_test.go
- internal/cmdutil/auth.go
This improves the handling of 404s when authenticated with a service token.
Since a 404 generally means the token does not have access to the resource, it's confusing that we say it's "not found".
`cmdutil.HandleNotFoundWithServiceTokenCheck(` can be added to more commands. Started with the two most common that trip people up (branch show and branch create).
**Invalid token:**
```
Error: Authentication failed. Your service token appears to be invalid.
You are currently authenticating using service tokens. Please check your service token credentials.
Service tokens can be provided in two ways:
1. Environment variables: PLANETSCALE_SERVICE_TOKEN_ID and PLANETSCALE_SERVICE_TOKEN
2. Command-line flags: --service-token-id and --service-token
To create a new service token, run: pscale …
```
> Improve service token auth error messages

- go.mod
- go.sum
- internal/cmd/backup/restore.go
- internal/cmd/backup/restore_test.go
- internal/cmd/branch/branch.go
- internal/cmd/branch/create.go
- internal/cmd/branch/create_test.go
- internal/cmd/branch/delete.go
- internal/cmd/branch/delete_test.go
- internal/cmd/branch/list.go
- internal/cmd/branch/list_test.go
- internal/cmd/branch/schema.go
- internal/cmd/branch/schema_test.go
- internal/cmd/branch/show.go
- internal/cmd/branch/show_test.go
- internal/mock/branch.go
This pull request implements handling of the Postgres branches in our backup restore and branch commands, since the shape of the `PostgresBranch` model differs from that of `DatabaseBranch`.
> Implement commands for Postgres branches

- internal/cmd/database/database.go
- internal/cmd/database/show_test.go
Example:
```
NAME (4)             KIND         CREATED AT    UPDATED AT
-------------------- ------------ ------------- ----------------
testdb               mysql        1 month ago   31 minutes ago
another-test         mysql        1 month ago   31 minutes ago
mydb                 mysql        1 month ago   31 minutes ago
pg                   postgresql   1 week ago    1 week ago
```
> Update database list/show to include `kind`

- internal/cmd/role/create.go
- internal/cmd/shell/shell.go
- internal/cmdutil/cmdutil.go
- internal/roleutil/roleutil.go
`pscale shell` works for Postgres databases now.  Unlike Vitess, for Postgres, we just use `psql` to connect directly to the database, with no local proxy required.
`--replica` connects to a read-only replica.  `--role` allows `reader`, `writer`, `readwriter`, and `admin` roles, the same as Vitess.
We always connect to :5432, rather than the pooler on port :6432.  We're creating an ephemeral account, and poolers have to give each different account its own connection, so we'd never get pooled.  Why pay the extra hop for no benefit?
> Implement `pscale shell` for Postgres

- internal/cmd/root.go
Changed the title from 'Database management' to 'General database commands' to better reflect the nature of the commands in this group.
> Update database command group title to 'General database commands'

- internal/cmd/keyspace/create.go
Similar to branch creation and deploy requests, support a `keyspace create --wait` flag that exits when the keyspace has initialized.
> Add `--wait` flag to keyspace create

- internal/cmd/branch/create.go
Increase to 10 minutes to handle for larger multi keyspace branches
> Extend timeout for database branch readiness checks
